### ISSUE TITLE
OAuth2 Example Client doesn't have ADMIN scope

### ISSUE THREAD

**Issue by facundofarias** [osiam/osiam#129]
[Installation and configuration guide](ttps://github.com/osiam/osiam/blob/master/docs/detailed-reference-installation.md#default-setup) states that:

> OSIAM also creates an initial OAuth 2 client:
> Client ID: example client
> Client secret: secret
> Client redirect URI: http://localhost:5000/oauth2
> Client scopes: ADMIN

However, as far as we can see on the [init_db](https://github.com/osiam/osiam/blob/master/src/main/resources/db/migration/postgresql/V1__init_db.sql) script, the example client doesn't have ADMIN scope. Which one is wrong? The script or the docs?

Thanks a lot!

**Comment by dacrome** [comment]
Hi @facundofarias,

in OSIAM any database change will be done by a Flyway script, to make a version switch as easy as possible. As we introduced Flyway, OSIAM knows the scopes which are used in the [init_db](https://github.com/osiam/osiam/blob/master/src/main/resources/db/migration/postgresql/V1__init_db.sql#L1070) script: `GET`, `POST`, `PUT`, `PATCH`, `DELETE`. As switched to the new ones, `ADMIN` and `ME`, the old ones needs to be removed, which is done with [Java](https://github.com/osiam/osiam/blob/master/src/main/java/db/migration/V4__replace_old_scopes.java), because it's too complex to do that with SQL.
So to answer your question, the docs and the scripts are both up-to-date.
