### ISSUE TITLE
Finish for 5- and 10-min quickstart documents.

### ISSUE THREAD

**Issue by thomasdarimont** [osiam/osiam#22]
Currently the 5- / 10-min descriptions in the [docs](https://github.com/osiam/osiam/tree/master/docs) are empty.

It would be great to have them since new users are most likely to look at those first.

**Comment by tkrille** [comment]
Hi @thomasdarimont,

you're absolutely right. Unfortunately, there was still no time to do this, yet. I'm looking forward to write something this week. I'm kind of responsible for the quickstarts.

**Comment by tkrille** [comment]
This is blocked, because I cannot link to any artifact for downloading. The snapshots in OSS JFrog are always a moving target. @dacrome I need some stable artifact, like `osiam-latest.war` (like [suggested by me](https://github.com/osiam/osiam/issues/194#issuecomment-223819026)), so I can link to it form the quick start.

Btw: Due to the latest changes to OSIAM's process of deployment, it will only be 1 simple quick start, that I'll put in the README.

**Comment by dacrome** [comment]
@tkrille when #226 is merged you can link to https://dl.bintray.com/osiam/downloads/osiam/latest/osiam-latest.war

**Comment by dacrome** [comment]
@tkrille Updated my [comment](https://github.com/osiam/osiam/issues/22#issuecomment-224438405) because the link changed

**Comment by tkrille** [comment]
Thanks @dacrome
