### ISSUE TITLE
Feature support - Bulk Create and Database support

### ISSUE THREAD

**Issue by tusharparate1** [osiam/osiam#253]
Hi Team,
This is Tushar here and currently working at MetricStream Inc (http://metricstream.com). 
We wanted to consume OSIAM for our SCIM implementation in our product but need few clarification on following:
1. Upto when (date) OSIAM v2 will support BULK operation?
2. What are the other database supported by OSIAM apart from H2, PostgreSQL and MySQL database?
Does OSIAM will work with Oracle database?

Thanks,
Tushar

**Comment by wallner** [comment]
Hello Tushar,
thank you for considering OSIAM for your use case. Let me try to answer your questions. 
1. OSIAM v2 is never going to support BULK operations, since it is in maintenance only mode. All further development is happening on releases following OSIAM 3.0., which was released recently and we would urge you to upgrade. That beeing said: At the moment we have no time frame for the implementation of BULK operations,since we don't really have a need for them. If they are something you need, I would ask you to file a bug, please. We can however make no promises about the ETA.
2. Other than the three databases you mentioned we don't support any. It is not too unlikely that OSIAM "just works" on other databases once we have a flyway migration for it in place. We would be happily add Oracle to the list of supported databases, but would need a way to test the setting. We do this by using Docker, so we would need an Oracle Docker image. Again, as in the first question, please file a bug if that feature is important to you, so that we can track the progress there, however we can not make any promises regarding the time frame.

I hope my answers helped you at least a little bit.

Regards,
---Florian

**Comment by wallner** [comment]
Hello @tusharparate1,
I hope that I answered your questions. I will close the issue for now. If you have any further questions don't hesitate to ask.
