### ISSUE TITLE
External JDBC user store as the primary user store of the OSIAM  

### ISSUE THREAD

**Issue by Vindulamj** [osiam/osiam#255]
Can we connect a external JDBC user store as the primary user store of OSIAM rather than using the internal one? If yes could you suggest me some documentation where I can follow to get it done?

**Comment by wallner** [comment]
Hello @Vindulamj,
At the moment the only connector we provide is one for LDAP. We don't really have plans to create one for external JDBC data stores, since we don't have the need for it. We would not not be opposed to add one to the project if you (or somebody else) came up with one, though.

Regards,
---Florian

**Comment by Vindulamj** [comment]
Hi @wallner 
Thanks for the quick info. Currently I am evaluating the OSIAM for a project. I will consider about what you have said. 

Regards,
-Vindula

**Comment by wallner** [comment]
Hello @Vindulamj,
thank you for evaluating OSIAM, I'm closing this issue for now. Please don't hesitate to open another one any time.

Regards,
---Florian
