### ISSUE TITLE
OSIAM opens additional random port

### ISSUE THREAD

**Issue by smancke** [osiam/osiam#272]
When starting osiam, it opens a second port on a random port number.
Don't know what that is good for, maybe JMX or something?

Example: 
$ ./osiam-3.0.war
.. Starting Osiam on smob with PID 7628 ..

$ sudo netstat -tulpn| grep 7628
tcp6       0      0 :::8080                 :::*                    LISTEN      7628/java       
tcp6       0      0 :::33860                :::*                    LISTEN      7628/java

**Comment by tkrille** [comment]
Hi @smancke,

this port is opened automatically by the H2 JDBC driver. In its [default configuration](https://github.com/osiam/osiam/blob/master/src/main/resources/home/config/osiam.yaml#L40), OSIAM uses a file-based H2 database with [automatic mixed mode](http://www.h2database.com/html/features.html#auto_mixed_mode). So the port you are seeing, is the one used by the embedded H2 Server.

**Comment by smancke** [comment]
Hi @tkrille,
but isn't this a very bad default configuration?
If someone uses osiam with H2, all access to the data store is totally unsecured.

**Comment by tkrille** [comment]
Hello @smancke,

the default configuration only serves one single purpose: to get OSIAM running as quickly as possible for testing, debugging, integrating your app with OSIAM and for developing OSIAM itself. It's not meant to be used in any production like environment. But the reason for this is not security. It's that you will eventually lose all your data, when using a file-based H2 database. In terms of security, H2's [automatic mixed mode](http://www.h2database.com/html/features.html#auto_mixed_mode) actually is secure, because:

* the port is random: "The first connection automatically starts a server on a random port."
* you can only connect to it, if you also have read access to the database file: "The IP address and port of the server are stored in the file .lock.db […]."
* the embedded server, that gets started, uses a random password: "[…] the client reads .lock.db file and sends the the random key that is stored there to the server"

This doesn't seem insecure to me.

**Comment by tkrille** [comment]
Hi @smancke,

did my last comment answer your question?

**Comment by smancke** [comment]
ok @tkrille thanks for clarifying!
