### ISSUE TITLE
Question: Why we are not adding group in UserEntity

### ISSUE THREAD

**Issue by tusharparatemsi** [osiam/osiam#296]
Hi Team,
Could you please clarify the following:
We have added all the fields in UserEntity in UserConverter.fromScim(User user). 
Is there any reason why a Group is not added in UserEntity in UserConverter.fromScim(User user) method.
Also why the method is deprecated: .setGroups(entityGroupsToScim(entity.getGroups()))

Or am I missing any thing in the implementation.

Thanks,
Tushar

**Comment by tkrille** [comment]
Hi @tusharparatemsi,

the `fromScim` method in `UserConverter` is only used for creating and updating a user. You cannot set the groups of a user when creating or updating them. This is mandated by the SCIM 2.0 spec. It says the following about the [`groups` attribute of a user](https://tools.ietf.org/html/rfc7643#page-25):

> Since this attribute has a mutability of
> "readOnly", group membership changes MUST be applied via the
> "Group" Resource (Section 4.2).

So it does not set the group, because that's not allowed.

To answer your second question: I'm assuming it is about [this line](https://github.com/osiam/osiam/blob/bfb4ab3323baf0473d556460858393f8b4433c41/src/main/java/org/osiam/resources/converter/UserConverter.java#L190). I cannot see any deprecation in the code. Are you using the SCIM classes of the connector? Specifically, are you asking why [this method](https://github.com/osiam/connector4java/blob/master/src/main/java/org/osiam/resources/scim/User.java#L979) is deprecated? It's deprecated for the same reasons, as the `fromScim` method in `UserConverter` is not setting the groups of a User: You cannot set the groups of a user on the user themselves. You can only do this on the group. The method is a residue of the time, when the server and client shared the SCIM classes. I hope this answers your questions.

**Comment by tkrille** [comment]
I'm closing this for now. If you have further questions, feel free to open this issue again, @tusharparatemsi.
