### ISSUE TITLE
AJP support in 3.0+

### ISSUE THREAD

**Issue by timopick** [osiam/osiam#88]
We should retain the support of AJP13 in 3.0+ for loadbalancing purposes.

http://www.appsdev.is.ed.ac.uk/blog/?p=525

**Comment by dacrome** [comment]
We decided not to migrate to fatjar. We believe that it is a good idea to stay with the war, which is also runnable as standalone application (so it's a fatwar). So if you need to use AJP, you can still use it when deploying the fatwar to an external tomcat. I don't think it is a good idea to support this with the standalone applications, because OSIAM can not be load balanced with its state.

**Comment by timopick** [comment]
If it's ok with you, I'd like to keep this issue open until AJP functionality has been proved working with 3.0. Just so we don't forget that AJP connectivity is actively used in some projects and thus has to be retained.

**Comment by tkrille** [comment]
> Just so we don't forget that AJP connectivity is actively used in some projects and thus has to be retained.

Then, IMHO, we should offer this functionality in the standalone version too, because I suppose, that these projects also want to migrate to the standalone version eventually.
