### ISSUE TITLE
Unable to filter resource by extension field

### ISSUE THREAD

**Issue by xaviarias** [osiam/osiam#94]
Hi, 

When querying a user to the OSIAM resource server with a multi-filter including an extension field, the server responds with this error:

`Could not deserialize the error response for the HTTP status 'Conflict'. Original response: {"error_code":"CONFLICT","description":"Filtering not possible: 'urn:com.mycompany:scim:extensions:1.0:client' not available"}`

The extension is valid and user has a defined value for the `client` field. 

Is this a bug or a SCIM feature not yet implemented?

**Comment by wallner** [comment]
Hello @xaviarias,
We need more information from you to solve this. The error you provide indicates that the extension you try to filter the field of doesn't exist. Could we maybe see the query string? I also noticed that you filter on your extension name with the fully qualified URN, ie it starts with `urn:` is that intentional? I expect your filter to work if you drop the first `urn:` and just filter for the field name ie. `com.mycompany:scim:extensions:1.0:client eq <some string>`.

Please note, that we don't really support the filtering by schemas as defined in section [3.4.2.2.  Filtering](https://tools.ietf.org/html/rfc7644#section-3.4.2.2):

> Clients MAY query by schema or schema extensions by using a filter expression including the "schemas" attribute

Which means that something like this is doesn't work: `filter= schemas eq "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"`

But if I understand you correctly that is not what you want to do, right? you want to filter on an extension _field_. Please try dropping the initial `urn:`

After reading the RFC again I think we might actually be wrong here, I feel the RFC is a little ambiguous with regard to filtering on extension fields. What is your opinion on this should filtering on extension fields always require the fully qualified URN including `urn:`, or to not break OSIAMs backward compatibility at least not fail on it?

That said, taking a look at the [code](https://github.com/osiam/osiam/blob/4745cafee0ad6f9637b413333d07b353f717f019/src/main/java/org/osiam/storage/query/UserSimpleFilterChain.java#L65-L65) of OSIAM in question I think we do habe a bug here in that we identify the field of the extension by locating the last period in the string and using that as the field name to search for. So turning your filter string into something like `com.mycompany:scim:extensions:1.0.client eq <some string>` should work as a workaround. Sorry for the inconvenience.

**Comment by wallner** [comment]
So, come to think of it: If the extension is actually registered with the fully qualifying URN and is valid as you say,  dropping the leading `urn:` is probably not making a difference. The bug is definitely the last period `.` separating the extension field from the urn.

Can you verify that by changing the query in that regard? If that works, we can provide a fix in a short time. However we still need to agree on the correct way to handle searching of extensions.

**Comment by tkrille** [comment]
Yes, that's a bug on our side. We only support `.` as a separator of URN and field name. This is wrong according to the RFC. So it must be changed to support `:`. I suggest that we should still support the `.` as separator for backwards compatibility.

**Comment by tkrille** [comment]
> However we still need to agree on the correct way to handle searching of extensions.

It must be a `:` according to the ABNF here: http://tools.ietf.org/html/rfc7644#page-21

**Comment by tkrille** [comment]
I've just looked up the code: https://github.com/osiam/osiam/blob/master/src/main/java/org/osiam/storage/query/UserSimpleFilterChain.java#L65

Seems rather easy to fix.

**Comment by wallner** [comment]
@tkrille I agree with you, however for the last few years we have been accepting periods to separate the extension field from the URN. So my plan would be the following:
- Try to resolve the field by checking for a colon `:` as separator.
- If we can't find one try to resolve it by looking for a period `.` as separator.
- If we find one, use the identified field name but make sure to generate a warning that we are going to stop supporting periods as separator in the future.
  Does that work for you @xaviarias?

**Comment by tkrille** [comment]
Yes, we should issue a warning, if `.`-separated filters have been used.

**Comment by xaviarias** [comment]
Hi @wallner and @tkrille,

That would be fine for us since we only use simple attributes, but bear in mind that complex attributes may have sub-attributes separated by '.' as stated in the SCIM RFC (https://tools.ietf.org/html/draft-ietf-scim-api-00#section-3.8).

So maybe it should be worth to implement a resolver that can handle both kind of attributes, simple and complex. This is of course up to you :)

For the moment we have a workaround that filters results once they are retrieved.

Thanks for your help !

**Comment by xaviarias** [comment]
Regarding the filtering by schemas as commented by @wallner, we use the OSIAM connector to query user resources, actually I ignore what is happening under the hood.

**Comment by wallner** [comment]
Hello @xaviarias,

sadly complex types are not supported by our implementation of extensions at the moment and changing that without a critical performance hit is not a trivial task due to the way we implemented extensions and are using a relational database as storage, so we can't promise that for the near to mid-term future.

**Comment by tkrille** [comment]
Of course, if you really, really need complex extension fields @xaviarias, then we can certainly figure something out, even in short-term :)

**Comment by xaviarias** [comment]
Hi @wallner and @tkrille, we use only two simple attributes. Thanks for your support!
